language: python
python:
  - '2.7'
  - '3.4'
env:
  - DJANGO="requirements"
  # - DJANGO="https://github.com/django/django/archive/master.zip#egg=django"
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == '3.4' ]]; then REQ_VERSION=3; else REQ_VERSION=2; fi
  - REQUIREMENTS="requirements$REQ_VERSION.txt"
  - pip install virtualenv
  - virtualenv env
  - source env/bin/activate
  # - pip install -r "$REQUIREMENTS" --download-cache $HOME/pip-cache
  # - if [[ "requirements" != "$DJANGO" ]]; then pip install --upgrade "$DJANGO"; fi
  - pip install flake8 isort
  - env
  - which flake8
  - which isort
script:
  - flake8 app
  - echo "[settings]" > $HOME/.isort.cfg && echo "skip=migrations" >> $HOME/.isort.cfg
  - isort --check-only -rc app
  - python manage.py test
services:
  - redis-server
  - memcached
  - rabbitmq
addons:
  postgresql: '9.3'
before_install:
  - psql -c 'create database app;' -U postgres
cache:
  directories:
    - $HOME/pip-cache
