language: python
python:
  - "2.7"
install:
  - pip install virtualenv
  - virtualenv env
  - source env/bin/activate
  - pip install setuptools==9.1
  - pip install -r requirements.txt
script:
  - flake8 app
  - frosted -r app
  - cp .isort.cfg $HOME/.isort.cfg
  - isort --check-only -rc app --diff
  - cd app
  - python manage.py test -v 2 --with-coverage
services:
  - redis-server
  - rabbitmq
addons:
  postgresql: "9.3"
before_install:
  - psql -c "create database app;" -U postgres
notifications:
  slack: yaga:ESVnfpnyr7Xxr0CXzxB7q4ye
