language: python
python:
  - '2.7'
  - '3.4'
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then REQ_VERSION=3; else REQ_VERSION='' fi
  - pip install -r $(echo $REQ_VERSION) --download-cache /home/travis/pip-cache
script:
  - flake8 app
  - cd app && python manage.py test
services:
  - redis-server
  - memcached
  - rabbitmq
addons:
  postgresql: '9.3'
before_install:
  - psql -c 'create database app;' -U postgres
cache:
  directories:
    - /home/travis/pip-cache
    - /home/travis/virtualenv/python2.7
    - /home/travis/virtualenv/python3.4
