language: python
python:
  - '2.7'
  - '3.4'
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install -r requirements3.txt; else pip install -r requirements.txt; fi
script:
  - flake8 app
  - cd app && python manage.py test
services:
  - redis-server
  - memcached
  - rabbitmq
addons:
  postgresql: '9.3'
before_install:
  - psql -c 'create database app;' -U postgres
