"""empty message

Revision ID: 553f8d28bb2b
Revises: 3e357c586295
Create Date: 2014-12-16 12:20:21.896117

"""

# revision identifiers, used by Alembic.
revision = '553f8d28bb2b'
down_revision = '3e357c586295'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('last_ip', sa.String(length=255), nullable=False, server_default='127.0.0.1'))
    op.add_column('session', sa.Column('last_usage', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'last_usage')
    op.drop_column('session', 'last_ip')
    ### end Alembic commands ###
